### ISSUE TITLE
Rewrite abstract, intro and diagram to use JOSE/COSE centric

### ISSUE THREAD

**Issue by awoie** [vcstuff/draft-ietf-oauth-status-list#110]
The abstract, intro, diagrams wrt referenced tokens description should refer to COSE and JOSE instead of CWT/JWT. Otherwise, non-CWT COSE objects such as ISO 18013-5 MSO cannot use this spec. Same applies to SD-JWT VC encoded secured using JWS.

**Comment by paulbastian** [comment]
We adjusted the terminology already, but the text in the introduction is not matching yet
