### ISSUE TITLE
Title / Future Proofness for other formats than bitarrays

### ISSUE THREAD

**Issue by paulbastian** [vcstuff/draft-ietf-oauth-status-list#21]
I'm wondering whether
a) this document shall always only be about status list using bitarrays/bitstrings
or
b) we want to leave a window open to enable other forms of storage

In case of a) it could make sense to name bit array in the title of the document.
In case of b) it could make sense to add a field that reference the existing mechanism

**Comment by mprorock** [comment]
for this reason we are moving the equivalent to this work at w3c to something like "bitstringstatuslist" to avoid squatting on the broad concept of status list

**Comment by paulbastian** [comment]
Linked to #77

**Comment by paulbastian** [comment]
Solved by #85
