### ISSUE TITLE
JOSE typ for Status List Token

### ISSUE THREAD

**Issue by paulbastian** [vcstuff/draft-ietf-oauth-status-list#25]
> umm I thought we agreed to remove the concept of the "typ" attribute.. so no `revocation-list` and no `suspention-status-list`.

But I assume the Status List Token will have a `typ` JOSE header to properly distinguish it from other JWTs, right?

_Originally posted by @tlodderstedt in https://github.com/vcstuff/draft-looker-jwt-cwt-status-list/issues/17#issuecomment-1584372077_

**Comment by Sakurann** [comment]
my original comment should be removed from the description because I was referring to the `type` JWT claim. 
for the purpose of this issue, simply put, a status list JWT should be typed per JWT BCP. and I would not expect any objections to that..

**Comment by Sakurann** [comment]
yes!

**Comment by paulbastian** [comment]
It's available in the example https://vcstuff.github.io/draft-looker-oauth-jwt-cwt-status-list/draft-looker-oauth-jwt-cwt-status-list.html#section-4.2-3 but its missing from the text. In general some text about header parameters is needed

**Comment by paulbastian** [comment]
Solved by #71
