### ISSUE TITLE
Document the CWT variation of the status list

### ISSUE THREAD

**Issue by tplooker** [vcstuff/draft-ietf-oauth-status-list#3]
As described in the title, detail the CWT representation of the status list which is complementary to the JWT representation.

**Comment by bc-pi** [comment]
Maybe a naive question but what's the motivation for this draft having the two representations? When positioned
as a companion of the SD-JWT VC draft and aiming for the OAuth WG, it seems like keeping the scope tighter and only having the JWT representation would be sufficient/okay/preferable.

**Comment by tplooker** [comment]
@bc-pi, credential formats like mDocs do not have a status/revocation mechanism hence a CWT based representation is beneficial to these applications.

**Comment by bc-pi** [comment]
I dunno, I'm not convinced that necessitates having multiple status list token representations. Especially in one draft. This draft, which again is being positioned as a companion to the SD-JWT VC. I suspect the work would be more palatable for adoption with a scope that's reflective of that. But maybe that's just me. Thanks for the context.
