### ISSUE TITLE
Use zlib instead of Gzip?

### ISSUE THREAD

**Issue by paulbastian** [vcstuff/draft-ietf-oauth-status-list#39]
Gzip is for files and uses zlib internally

**Comment by paulbastian** [comment]
After some research to the difference between gzip, zlib and Deflate, I would propose to consider zlib instead Gzip:
- both rely on Deflate compression algorithm
- Gzip is more focused on files
- Gzip contains more metadata that we do not need as they are redundant in JWT or deprecated (modifytime, content type)
- header is a little smaller

**Comment by bc-pi** [comment]
(apologies in advance for any misunderstanding/confusion around the relationship between gzip, zlib, and Deflate) but FWIW JWE uses DEFLATE/RFC1951 directly for its optional compression https://datatracker.ietf.org/doc/html/rfc7516#section-4.1.3 (and there's one example test in https://www.rfc-editor.org/rfc/rfc7520.html#section-5.9.4), which might be an option here.

**Comment by paulbastian** [comment]
add recommendation for BEST_COMPRESSION mode

**Comment by paulbastian** [comment]
Solved in #80
