### ISSUE TITLE
key resolution

### ISSUE THREAD

**Issue by paulbastian** [vcstuff/draft-ietf-oauth-status-list#45]
Do we want normative text/options for key resolution?

**Comment by c2bo** [comment]
We should use whatever the referenced token is using for key resolution and put it out of scope for this spec?

**Comment by paulbastian** [comment]
spec should say that key resolution is out of scope

**Comment by c2bo** [comment]
Should be defined elsewhere - e.g., https://github.com/vcstuff/oid4vc-haip-sd-jwt-vc/issues/65

**Comment by paulbastian** [comment]
Should we add this to design considerations? #75

**Comment by c2bo** [comment]
Good point. It would probably make sense to point that out in the spec itself (remark that it is out of scope).
