### ISSUE TITLE
Add claim for used compression algorithm

### ISSUE THREAD

**Issue by c2bo** [vcstuff/draft-ietf-oauth-status-list#50]
We should consider to add a claim into the status list token that describes the used compression algorithm. This would allow us to easily adopt other options for compression.

**Comment by paulbastian** [comment]
I'm ok as long as we restrict the mandatory or allowed algorithms to 1 to start with

**Comment by c2bo** [comment]
Yeah, I would see it as an extension point for the future. Initially I do believe, we should start with one option.

**Comment by paulbastian** [comment]
Use `_alg` claim, SHA-256 as mandatory default algorithm

**Comment by paulbastian** [comment]
@c2bo @tplooker and me agreed to not add this feature as
- the is no reason currently as we do not envision other compressions
- this mechanism could easily be added in backwards-compatible fashion later on
- there would be no implementation logic for this claim right now
- we are missing a registry for compression algs

**Comment by paulbastian** [comment]
pending close
