### ISSUE TITLE
Slight difference in compression result

### ISSUE THREAD

**Issue by TimoGlastra** [vcstuff/draft-ietf-oauth-status-list#67]
I'm working on a TypeScript implementation of this spec, and have the encoding / decoding of the status list implemented. It seems to work based on the example in the spec and the example python scripts, with one slight difference.

When I encode either the 1 or 2 bit example it will output one character difference `_`, while mine outputs an `A`. The decoding seems to work fine, and maybe this is a gzip thing, but I'm wondering if the examples use certain gzip features to get this output?

I've adapted my implementation to use compression level 9 (default for python `gzip` lib) and set the mtime to the same value

The input byte array is the same as for the python implementation and the examples in the spec, so it's really something that is happening during the gzip encoding (the output byte array here is different)

```
H4sIAMo_jGQCA9u5GABc9QE7AgAAAA
H4sIAMo_jGQCAzvp8hMAZLRLMQMAAAA
```

```
H4sIAMoAjGQCA9u5GABc9QE7AgAAAA
H4sIAMoAjGQCAzvp8hMAZLRLMQMAAAA
```

any idea what is going on here? 

The implementation and tests can be found here: https://github.com/TimoGlastra/jwt-status-list-ts

**Comment by c2bo** [comment]
Seems to be a difference in the header - from the position I would assume the timestamp (even though you seem be setting it to the fixed value used in the examples in the draft)? There is also a header entry for the operating system - that would also be a very likely candidate for the difference. I will take a look at it when I am back from IIW.

We were discussing switching from gzip to zlib (or deflate directly) for that reason - we don't really need these headers and most languages seem to support both gzip and zlib (which was our concern when we initially thought about this).
Related Issue: #39

**Comment by paulbastian** [comment]
Thanks for testing!

There is a header as well in zlib, but it's considerably smaller. The zlib header does not include a timestamp which makes it better for reproducible results and test vectors.

I think we should also give a recommendation for the used compression level, I suspect either default or highest.

It would be interesting if the underscore vanishes in zlib?

**Comment by c2bo** [comment]
I changed the python implementation to use zlib with level 9 and did the same for your typescript implementation --> both resulted in the same:
```
eNrbuRgAAhcBXQ
eNo76fITAAPfAgc
```
We should really change that imho (and also add the text to recommend compression level).

**Comment by TimoGlastra** [comment]
I'm a proponent of using zlib instead of gzip. As suggested in the other issue, we don't really need the other metadata. And the result is smaller as well :)
