### ISSUE TITLE
Call for Adoption Feedback: Draft Title

### ISSUE THREAD

**Issue by paulbastian** [vcstuff/draft-ietf-oauth-status-list#74]
https://mailarchive.ietf.org/arch/msg/oauth/hSOvzlKZTUJpI8ucB1CLNo5koqg/

> The first draft of the OAuth WG should rather be called: 
> *draft-oauth-status-list-token-00

https://mailarchive.ietf.org/arch/msg/oauth/bO9FXfCvvIsxNz-0cnEnpDDh8mE/

> I do think the document would be more appropriately scoped with more focus
> on the status list itself and less so on the JWT/CWT signed representations
> thereof. As such, I'd suggest maybe using a less specific docname without
> the jwt-cwt bit if/when it moves to a WG draft. Something
> like draft-ietf-oauth-token-status-list.
+2 from Nat and Vladimir

**Comment by tlodderstedt** [comment]
If think draft-oauth-status-list is sufficient.

**Comment by bc-pi** [comment]
> think draft-oauth-status-list is sufficient.

Aggree but an official WG draft in the OAUTH WG needs to start w/ `draft-ietf-oauth-` so it'd be `draft-ietf-oauth-status-list`

**Comment by paulbastian** [comment]
I would be fine with draft-ietf-oauth-status-list. I don't see much benefit of naming it draft-ietf-oauth-token-status-list as you originally proposed.

**Comment by bc-pi** [comment]
> I would be fine with draft-ietf-oauth-status-list. I don't see much benefit of naming it draft-ietf-oauth-token-status-list as you originally proposed.

Agree that `draft-ietf-oauth-status-list` is probably better anyway

**Comment by selfissued** [comment]
I think that `draft-ietf-oauth-status-list` is a good identifier choice.  We'll never have to change it.

**Comment by tplooker** [comment]
I'm happy with `draft-ietf-oauth-status-list` also.

**Comment by c2bo** [comment]
Happy with `draft-ietf-oauth-status-list` as well.

**Comment by paulbastian** [comment]
Ok, then there is agreement on `draft-ietf-oauth-status-list`
