### ISSUE TITLE
typo/mixup in Status List JWT Format and Processing Requirements

### ISSUE THREAD

**Issue by bc-pi** [vcstuff/draft-ietf-oauth-status-list#78]
The [second bullet](https://www.ietf.org/archive/id/draft-ietf-oauth-status-list-00.html#section-4.1-2.2.1) in the "Status List JWT Format and Processing Requirements" section has 'The JWT MUST contain a "sub" (subject) claim that contains an unique string identifier for that **Referenced Token.**' but I believe it should be "... unique string identifier for that **Status List Token**."

**Comment by paulbastian** [comment]
that's correct, thanks for pointing this out Brian
