### ISSUE TITLE
IETF 118: Establish a mechanism that allows for other revocation means in the Referenced Token

### ISSUE THREAD

**Issue by paulbastian** [vcstuff/draft-ietf-oauth-status-list#85]
Leif asked to leave some space for future revocation mechanisms as StatusList might be only one approach.
The Structure in the Referenced Token should convey some kind of type, that enables other mechanisms reusing the "status" claim.

Related to #21 
Related to #40

**Comment by paulbastian** [comment]
Option 1:
```
"status_bitstring": {
    "idx": 0,
    "uri": "https://example.com/statuslists/1"
  }
```

Option 2:
```
"status": {
    "typ":"bitstring"
    "idx": 0,
    "uri": "https://example.com/statuslists/1"
  }
```

Option 3:
```
"status": {
    "idx": 0,
    "bitstring": "https://example.com/statuslists/1"
  }
```

**Comment by paulbastian** [comment]
We favor Option#2 currently

**Comment by paulbastian** [comment]
We need text for extension points

**Comment by awoie** [comment]
I'm still not convinced since I think new status methods could register a new claim. 

But if people want this, then there is another option which is similar to `cnf`:

```
"status": {
  "list": { ... }, 
  "ocsp": { ... },
  ...
}
```

**Comment by tlodderstedt** [comment]
new ways for doing status management can introduce new claims, so I prefer option 1 or 3.

**Comment by bc-pi** [comment]
> I'm still not convinced since I think new status methods could register a new claim.

I tend to agree with this (effectively option 1). There is already the extension point of defining a new claim for other revocation mechanisms. This draft doesn't need to accommodate extensibility.

**Comment by paulbastian** [comment]
@paulbastian and @c2bo favoring Oliver's option and will make an PR
