### ISSUE TITLE
DEFLATE in ZLIB

### ISSUE THREAD

**Issue by bc-pi** [vcstuff/draft-ietf-oauth-status-list#94]
maybe adjust the language around DEFLATE and ZLIB per [this thread](https://github.com/vcstuff/draft-ietf-oauth-status-list/pull/80/files#diff-2347c539b523e10cc060407bc8a517b0764d5a8da0b237be9899e1348dcd63c8R134) 

_Originally posted by @bc-pi in https://github.com/vcstuff/draft-ietf-oauth-status-list/pull/80#discussion_r1452588980_

**Comment by c2bo** [comment]
Copied over, to have everything in the issue here:
This is the current text:
> The complete byte array is compressed using the "DEFLATE" {{RFC1951}} compression method and stored using the "ZLIB" {{RFC1950}} data format. Implementations are RECOMMENDED to use the highest compression level available.

This is the proposal:
>The complete byte array is compressed using DEFLATE {{RFC1951}} inside the ZLIB {{RFC1950}} data format. Implementations are RECOMMENDED to use the highest compression level available.

I agree that the current text is a bit weird and I wasn't really sure how to formulate it better when writing it.

**Comment by bc-pi** [comment]
![Screenshot 2024-01-16 at 7 08 02 AM](https://github.com/vcstuff/draft-ietf-oauth-status-list/assets/71398439/f559cb78-2cb9-49f8-9a0b-c8c210de8644)
