### ISSUE TITLE
Consider including next update time claim for Status List

### ISSUE THREAD

**Issue by awoie** [vcstuff/draft-ietf-oauth-status-list#96]
To provide guidance for caching it might make sense to include a next update time in the status list. Or does `exp` provide this guidance?

**Comment by c2bo** [comment]
That information should be conveyed using http caching information:
> If caching is required (e.g., to enable the use of alternative mechanisms for hosting, like Content Delivery Networks), the control of the caching mechanism SHOULD be implemented using the standard HTTP Cache-Control as defined in {{RFC9111}}.

My understanding would be that `exp` provides the valdity of the information (can this be information be trusted/used for a verification/validation) and http caching information signals when the system should attempt to retrieve the information again. For this case the `expires` header from RFC9111 (https://datatracker.ietf.org/doc/html/rfc9111#section-5.3) would signal when the system fetching the status list tries to update again.

We have a TODO in the text right now to properly explain this mechanism:
> [10.2. ](https://vcstuff.github.io/draft-ietf-oauth-status-list/draft-ietf-oauth-status-list.html#section-10.2)[Cached and Stale status lists](https://vcstuff.github.io/draft-ietf-oauth-status-list/draft-ietf-oauth-status-list.html#name-cached-and-stale-status-lis)
TODO consumers/Relying Party of the status list should be aware if they fetch the up-to-date data

**Comment by awoie** [comment]
Perhaps we can keep this issue until we have the language in the caching section.

**Comment by awoie** [comment]
Would it make sense to add this if we assume the verifier is not fetching the status list themselves but only gets the status list from some other component? in that case, the reader would not have the caching info.

**Comment by paulbastian** [comment]
Yes, this issue keep coming up again and the given situation is a good reason to revisit this discussion.
However, we still need HTTP Cache for the unsigned Status List option

**Comment by paulbastian** [comment]
editors call:

- after exp token must be refreshed
- after ttl token may be refreshed
- duration vs point of time
- it should be a caching signal (like DNS), i.e. duration -> distribute caching/avoid spikes
- take fetching time as start interval instead of iat?
- information of ttl is informational, Verifiers may still recheck whenever say want

**Comment by tplooker** [comment]
Resolved by #101
